main: org.encanta.mc.ac.EncantaAC
#name: EncantaAC
name: UnrealPower
version: 10.2-U1
#author: Unity41
author: OpenSource
commands:
    upw:
        description: UnrealPower main command.
        permission: encanta.ac
        usage: wrong usage.
